name: finance_projects

channels:
  - conda-forge
  - defaults

dependencies:
  - python = 3.9
  - pandas
  - pandas-datareader
  - beautifulsoup4
  - scikit-learn
  - jupyterlab
  - matplotlib
  - mplfinance
  - pytest
  - requests
